### ISSUE TITLE
Request for a Xavier 2.73.9 release

### ISSUE THREAD

**Issue by alexgg** [balena-os/balena-jetson#159]
A user in the forums requires to use supervisor version 12.5.10 which is available on meta-balena 2.73.9.

**Comment by acostach** [comment]
Note: This request is not for the first generation of Xavier (AGX) as the title may suggest, but for the NX (see linked JF ticket).

We will do a release to include the fix for the hung tasks ticket too, after the Go rollback is complete in meta-balena. See https://github.com/balena-os/balena-jetson/pull/172

**Comment by acostach** [comment]
v2.80.3+rev1 is now available for the NX Devkit SD-CARD.
